//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class RunningEntities : DbContext
{
    public RunningEntities()
        : base("name=RunningEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Discipline> Disciplines { get; set; }
    public virtual DbSet<distance> distances { get; set; }
    public virtual DbSet<memberList> memberLists { get; set; }
    public virtual DbSet<race> races { get; set; }
    public virtual DbSet<runner> runners { get; set; }
}
