//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Discipline
{
    public int id { get; set; }
    public string Code { get; set; }
    public string Name { get; set; }
    public bool Active { get; set; }
}

public partial class distance
{
    public int EFKey { get; set; }
    public string Code { get; set; }
    public string Name { get; set; }
    public double Value { get; set; }
}

public partial class memberList
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public memberList()
    {
        this.races = new HashSet<race>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public Nullable<double> Distance { get; set; }
    public int Time { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<race> races { get; set; }
}

public partial class race
{
    public int Id { get; set; }
    public double distance { get; set; }
    public int time { get; set; }
    public int runner { get; set; }

    public virtual memberList memberList { get; set; }
}

public partial class runner
{
    public int EFKey { get; set; }
    public string firstname { get; set; }
    public string secondname { get; set; }
    public string ukan { get; set; }
    public Nullable<System.DateTime> dob { get; set; }
    public string email { get; set; }
    public Nullable<bool> Active { get; set; }
}
