//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunningModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventRunnerTime
    {
        public int EFKey { get; set; }
        public int RunnerId { get; set; }
        public int EventId { get; set; }
        public Nullable<int> Target { get; set; }
        public Nullable<int> Actual { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> RaceEventId { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual runner runner { get; set; }
    }
}
