//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunningModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceEvent
    {
        public int EFKey { get; set; }
        public int EventId { get; set; }
        public System.DateTime Date { get; set; }
        public bool Active { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
