//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunningModelA
{
    using System;
    using System.Collections.Generic;
    
    public partial class race
    {
        public int Id { get; set; }
        public double distance { get; set; }
        public int time { get; set; }
        public int runner { get; set; }
    
        public virtual memberList memberList { get; set; }
    }
}
