//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace runners
{
    using System;
    using System.Collections.Generic;
    
    public partial class runner
    {
        public int EFKey { get; set; }
        public string firstname { get; set; }
        public string secondname { get; set; }
        public string ukan { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string email { get; set; }
        public Nullable<bool> Active { get; set; }
        public string ageGradeCode { get; set; }
    }
}
